# List all available recipes
default:
    @just --list

# Set strict shell options for all recipes
set shell := ["bash", "-eux", "-c"]

# Update AWS credentials
auth:
    ~/.toolbox/bin/ada credentials update --account=026090537351 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE --once
    export AWS_DEFAULT_REGION='us-east-1'

# Remove virtual environment
clean:
    rm -rf .venv

install:
  #!/usr/bin/env bash
  set -eu
  if command -v uv &> /dev/null; then
    uv self update
  else
    curl -LsSf https://astral.sh/uv/install.sh | sh
  fi
  
  # https://docs.astral.sh/uv/reference/cli/#uv-sync
  uv sync
  source .venv/bin/activate


# Download podcast files
download_podcasts:
    curl -o ./podcasts/SCIM6456251481.mp3 https://dcs-spotify.megaphone.fm/SCIM6456251481.mp3?key=35e96ab6e76366104fc4100b969a39d5&request_event_id=ca383c29-36f0-4abd-9fb9-ac24dc64ca9f&timetoken=1728844385_528C76F0658DC9C55E80F982FFC903B3

# Set up EC2 environment
ec2_setup:
    curl https://pyenv.run | bash
    python3 -m pip install --user pipx
    python3 -m pipx ensurepath --force
    python3 -m pip install --user --upgrade pipx
    pipx install uv

# Set up macOS environment
mac_setup:
    # Install pyenv
    brew update
    brew install pyenv

    # Install uv
    brew install uv

# Run the agent with dev configuration
run_agent:
    .venv/bin/python src/holdon/agent/entrypoint.py dev

# Sync local directory with remote server
sync:
    #!/usr/bin/env bash
    LOCAL_DIR=$(pwd)
    PRIVATE_KEY="~/.ssh/samantha-ec2.pem"
    REMOTE_USER="ubuntu"
    REMOTE_HOSTNAME="ec2-18-215-251-169.compute-1.amazonaws.com"
    REMOTE_DIR="/home/$REMOTE_USER/workspace/Holdon"

    grep -v '^#' ".gitignore" | grep -v '^$' > ".syncignore"

    fswatch -o "$LOCAL_DIR" | while read; do
        rsync -avz --delete \
        -e "ssh -i $PRIVATE_KEY" \
        --exclude-from='.syncignore' $LOCAL_DIR \
        $REMOTE_USER@$REMOTE_HOSTNAME:$REMOTE_DIR
    done
