# List all available recipes
default:
    @just --list

# Set strict shell options for all recipes
set shell := ["bash", "-eux", "-c"]

# Update AWS credentials
auth:
    ~/.toolbox/bin/ada credentials update --account=026090537351 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE --once
    export AWS_DEFAULT_REGION='us-east-1'

# Remove virtual environment
clean:
    rm -rf .venv

install:
  #!/usr/bin/env bash
  set -eu
  if command -v uv &> /dev/null; then
    uv self update
  else
    curl -LsSf https://astral.sh/uv/install.sh | sh
  fi
  
  # https://docs.astral.sh/uv/reference/cli/#uv-sync
  uv sync
  source .venv/bin/activate

# Run the agent with dev configuration
run_agent:
    .venv/bin/python src/holdon/agent/entrypoint.py dev

serve-livekit:
    livekit-server --dev --bind 0.0.0.0
