[project]
name = "backend"
version = "0.1.0"
description = "backend"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "aioboto3>=13.1.1",
    "aiohttp>=3.10.10",
    "aiostream>=0.6.3",
    "boto3>=1.34.70",
    "dynaconf>=3.2.6",
    "fastapi>=0.115.12",
    "ffmpeg-python>=0.2.0",
    "httpx>=0.27.2",
    "jsonpath-ng>=1.5.3",
    "livekit-agents~=1.0rc0",
    "livekit-plugins-deepgram~=1.0rc0",
    "livekit-plugins-elevenlabs~=1.0rc0",
    "livekit-plugins-openai~=1.0rc0",
    "livekit-plugins-silero~=1.0rc0",
    "openai-whisper==20240930",
    "pygame>=2.6.1",
    "pipecat>=0.3.0",
    "pydantic>=2.10.2",
    "pyyaml>=6.0.2",
    "ruff>=0.11.2",
    "s3fs>=2024.9.0",
    "streamlit>=1.39.0",
    "uvicorn>=0.34.0",
    "websockets>=13.1",
    "langchain>=0.3.23",
    "matplotlib>=3.10.1",
    "langchain-anthropic>=0.3.10",
    "langchain-community>=0.3.21",
    "mem0ai>=0.1.81",
    "pillow>=11.1.0",
]

[tool.pytest.ini_options]
python_classes = ["Test", "Describe"]
python_functions = ["test_", "it_", "and_", "but_", "they_"]
python_files = ["test_*.py",]
testpaths = ["tests",]

[tool.uv]
package = true
