# List all available recipes
default:
    @just --list

# Set strict shell options for all recipes
set shell := ["bash", "-eux", "-c"]

# Update AWS credentials
auth:
    ~/.toolbox/bin/ada credentials update --account=026090537351 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE --once
    export AWS_DEFAULT_REGION='us-east-1'

# Remove virtual environment
clean:
    rm -rf .venv

install:
  #!/usr/bin/env bash
  # https://docs.astral.sh/uv/reference/cli/#uv-sync
  uv sync
  source .venv/bin/activate

# Run the agent with dev configuration
serve-agent:
    .venv/bin/python src/voice_agent/agent/entrypoint.py dev

# Start the FastAPI server
serve:
    @echo "Starting FastAPI server on http://0.0.0.0:8000"
    @.venv/bin/python -m src.control_server.main

# Start the FastAPI server in debug mode with more verbose output
serve-debug:
    @echo "Starting FastAPI server in debug mode on http://0.0.0.0:8000"
    @PYTHONPATH=. LOG_LEVEL=DEBUG .venv/bin/python -m src.control_server.main

serve-livekit:
    livekit-server --dev --bind 0.0.0.0
