// Define pixel colors
const OFF = '#374151';    // gray-700
const GREEN = '#22c55e'; // green-500

// 22x22 pixel data for a play icon (triangle pointing right)
export const PLAY_ICON: string[][] = [
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, GREEN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
];

export const PAUSE_ICON: string[][] = [
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, GREEN, GREEN, GREEN, GREEN, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
];