# List all available recipes
default:
    @just --list

# Set strict shell options for all recipes
set shell := ["bash", "-eux", "-c"]

# Remove virtual environment
clean:
    rm -rf .venv

install:
  #!/usr/bin/env bash
  # https://docs.astral.sh/uv/reference/cli/#uv-sync
  uv sync
  source .venv/bin/activate
