"use client";

import React from "react";
import PixelGrid from "../components/PixelGrid"; // Import the component

// Import components
// Define interfaces
//

// Define pixel colors (example using hex codes)
const OFF = '#374151'; // gray-700 (Tailwind)
const YELLOW = '#facc15'; // yellow-400 (Tailwind)
const BLUE = '#0ea5e9'; // sky-500 (Tailwind)
const RED = '#ef4444'; // red-500 (Tailwind)

// Example 22x22 pixel data for a smiley
const smileyData: string[][] = [
    [OFF, OFF, OFF, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, OFF, OFF, OFF, OFF],
    [OFF, OFF, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, OFF, OFF, OFF],
    [OFF, BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, YELLOW, YELLOW, BLUE, BLUE, OFF],
    [OFF, BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, YELLOW, YELLOW, BLUE, BLUE, OFF, OFF],
    [OFF, OFF, BLUE, BLUE, BLUE, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLUE, BLUE, OFF, OFF, OFF],
    [OFF, OFF, OFF, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, OFF, OFF, OFF, OFF],
    [OFF, OFF, OFF, OFF, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, OFF, OFF, OFF, OFF, OFF],
];

const Page: React.FC = () => {
    return (
        // Add centering styles
        <div className="flex min-h-screen items-center justify-center bg-gray-900">
            {/* Render the PixelGrid and pass the data */}
            <PixelGrid rows={22} cols={22} pixelData={smileyData} />
        </div>
    );
};


export default Page;
